- angular.json
- package-lock.json
- package.json
- tsconfig.json
intall bootstrap
looks cure
npm install bootstrap
<em>"Las niñas buenas se van al cielo, las malas se van conmigo"</em>
> feat: install bootstrap

- package-lock.json
- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/auth.service.spec.ts
- src/app/auth.service.ts
- src/app/auth/auth.component.html
- src/app/auth/auth.component.spec.ts
- src/app/auth/auth.component.ts
added auth component and service
> feat: added auth base

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/navbar/navbar.component.html
- src/app/navbar/navbar.component.ts
> added navbar

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/navbar/navbar.component.html
- src/app/schedule/training-session-list/training-session-list.component.html
- src/app/schedule/training-session-list/training-session-list.component.ts
- src/app/shared/interfaces/training-session.interface.ts
> feat: added schedule

- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/shared/interfaces/student.ts
- src/app/shared/services/student.service.ts
- src/app/student/student-list/student-list.component.html
- src/app/student/student-list/student-list.component.ts
> feat: list and delet TODO: reactive

- src/app/shared/interfaces/student.ts
- src/app/shared/services/student.service.ts
- src/app/student/student-list/student-list.component.ts
incremental student code and reactive list
<em>"sigan viendo"</em>
> feat: incrementeal student code and reactive student list

- package-lock.json
- src/app/schedule/training-session-list/training-session-list.component.html
> fix:schedule interface

- src/app/app.component.html
- src/app/navbar/navbar.component.html
- src/app/shared/services/training-session.service.ts
- src/app/student/add-student/add-student.component.html
- src/app/student/edit-student/edit-student.component.html
- src/app/student/student-list/student-list.component.html
- src/app/student/student/student.component.html
improve list view register student, access and search by name
looks gut
> feat: improve view

- src/app/auth/auth.component.ts
- src/app/shared/services/auth.service.ts
The auth component redirect to schedule when user is signedIn
> feat:Add user redirection upon signing in

- src/app/shared/interfaces/student.ts
- src/app/shared/services/student.service.ts
- src/app/student/add-student/add-student.component.html
- src/app/student/add-student/add-student.component.ts
- src/app/student/edit-student/edit-student.component.html
- src/app/student/edit-student/edit-student.component.ts
- src/app/student/student-list/student-list.component.html
- src/app/student/student-list/student-list.component.scss
edit student
to edit
forms
<em>"Mañana no hay desarrollo :)"</em>
> feat: edit student and improve student-list view

- src/app/student/add-student/add-student.component.html
- src/app/student/edit-student/edit-student.component.html
- src/app/student/edit-student/edit-student.component.ts
- src/app/student/student-list/student-list.component.html
- src/app/student/student/student.component.html
- src/app/student/student/student.component.ts
bianca profile
<em>"Bianca Buenaza Cuba Altanero"</em>
> feat: student profile

- src/app/app-routing.module.ts
- src/app/guard/guard.guard.ts
- src/app/shared/services/auth.service.ts
added authentication guard and fixed auth service 
> feat: authentication guard and fix auth service

- src/app/auth/auth.component.ts
- src/app/navbar/navbar.component.ts
Redirect when signed In and on sign-In/sign-Out button clicks
> feat:redirect when signed in

- package-lock.json
- src/app/shared/interfaces/attendance.ts
- src/app/shared/interfaces/payment.ts
- src/app/shared/interfaces/student.ts
> feat: new interfaces

- src/app/schedule/training-session/training-session.component.ts
- src/app/shared/helpers/date_helper.ts
- src/app/shared/services/student.service.ts
- src/app/student/add-student/add-student.component.ts
- src/app/student/student-list/student-list.component.html
- src/app/student/student-list/student-list.component.ts
- src/app/student/student/student.component.ts
edad en lista de estudiantes y nombre completo en perfil (mas compacto)
> refactor: student age and complete name in profile

- src/app/app-routing.module.ts
- src/app/schedule/training-session-list/training-session-list.component.ts
- src/app/schedule/training-session/training-session.component.html
- src/app/schedule/training-session/training-session.component.ts
- src/app/shared/helpers/date_helper.ts
- src/app/shared/services/attendance.service.ts
- src/app/shared/services/student.service.ts
- src/app/student/enroll-student/enroll-student.component.html
- src/app/student/enroll-student/enroll-student.component.ts
- src/app/student/student/student.component.html
feat: View list of previous attendances
feat: Save  attendance
feat: Select enrollment date 
fix: redirect when click enroll button
<em>"wujibifan"</em>
> feat: View list of previous attendance

- src/app/schedule/training-session/training-session.component.html
feat:improved training-session interface
> feat:improved training-session interface

- src/app/student/add-student/add-student.component.html
- src/app/student/student-list/student-list.component.html
- src/app/student/student-list/student-list.component.ts
search engine better than google's
<em>"oh oh oh it's magic you know"</em>
> feat: search students

- src/app/app-routing.module.ts
- src/app/schedule/training-session-list/training-session-list.component.ts
- src/app/schedule/training-session/training-session.component.html
- src/app/schedule/training-session/training-session.component.ts
> fix:select valid days only

- src/app/auth/auth.component.ts
feat:added alert when wrong credentials
> feat:added alert when wrong credentials

- src/app/student/student/student.component.html
- src/app/student/student/student.component.ts
feat: confirm withdraw student
> feat: confirm withdraw student

- src/app/student/add-student/add-student.component.html
- src/app/student/add-student/add-student.component.ts
- src/app/student/edit-student/edit-student.component.html
feat: improved register student interface
feat: improved edit student interface
> feat: improved register estudent interface

- src/app/shared/services/student.service.ts
- src/app/student/student-list/student-list.component.html
- src/app/student/student-list/student-list.component.ts
- src/app/student/student/student.component.ts
> feat: access by code

- angular.json
- src/app/document-generator/document-generator.component.ts
- src/app/payments-and-debts/payments-list/payments-list.component.ts
- src/app/shared/interfaces/attendance.ts
- src/app/shared/services/attendance.service.ts
- src/app/student/enroll-student/enroll-student.component.ts
- src/app/student/student/student.component.html
- src/app/student/student/student.component.ts
add assistance list in student profile
<em>"Concédeme la opción de oir tu eco"</em>
> feat: assistance list in student profile

- src/app/document-generator/document-generator.component.ts
> fix: fix mobile extension download

- src/app/app-routing.module.ts
- src/app/schedule/training-session/training-session.component.ts
- src/app/student/student/student.component.html
fix:attendance button on profile
> fix:attendance button on profile

- src/app/document-generator/document-generator.component.html
- src/app/schedule/training-session/training-session.component.html
- src/app/schedule/training-session/training-session.component.ts
bugs finales :p
<em>"La única constante en este mundo es el corazón voluble"</em>
> fix: date in trainig-session and spelling in documen-generation

- src/app/payments-and-debts/make-payment/make-payment.component.ts
- src/app/shared/services/payment.service.ts
- src/app/shared/services/student.service.ts
pagos fecha es mimimo entre today() y fecha de enrollment
<em>"Ojala no haya mas bugs por resolver :'v"</em>
> fix: fix de un bug de pagos

- src/app/schedule/training-session/training-session.component.ts
> hotfix: problemas de concurrencia al cargar asistencias

- src/app/schedule/training-session/training-session.component.html
- src/app/schedule/training-session/training-session.component.ts
hotfix: Update attendence when empty. Get previousAttendance when date changes.
feat: toggle saveAttendance button text between 'Edit' and 'Save'
<em>"Si se pudo" </em>
> hotfix: save attendence when empty

- src/app/app-routing.module.ts
- src/app/app.module.ts
- src/app/student/edit-enrollment/edit-enrollment.component.html
- src/app/student/edit-enrollment/edit-enrollment.component.ts
- src/app/student/student/student.component.html
feat: add edit student sessions
fix: register student when registered
<em>"Todo a su tiempo"</em>
> feat: add edit student sessions

- src/app/shared/helpers/date_helper.ts
<em>"Recuerda que te quiero"</em>
> dif: date fix

- src/app/payments-and-debts/debtors-list/debtors-list.component.html
- src/app/payments-and-debts/debtors-list/debtors-list.component.ts
- src/app/payments-and-debts/payments-list/payments-list.component.ts
- src/app/shared/helpers/student_helper.ts
- src/app/shared/interfaces/student.ts
- src/app/shared/services/student.service.ts
- src/app/student/add-student/add-student.component.html
- src/app/student/add-student/add-student.component.ts
- src/app/student/edit-student/edit-student.component.html
- src/app/student/edit-student/edit-student.component.ts
- src/app/student/student-list/student-list.component.html
- src/app/student/student-list/student-list.component.ts
- src/app/student/student/student.component.ts
new field in student, alias. It replaces first name + last name in students lists
to ease student search in lists, some students use their second name
just added
> feat: add alias to student

- .github/workflows/main.yml
> Pacha2880 patch 1
